add solution for lection3-modal
js-tasks-ru/htmlcss-20231222_svzhloba pull request #10
Opened 2024-01-24 20:09 UTC by Sansamania

2024-01-24 20:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-25 21:56 UTC, GSemikozov requested changes

2024-01-25 21:56 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  opacity: 0.5;
фон и полупрозрачность лучше объединить через rgba

2024-01-25 21:56 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  width: 100%;
+ top: 0; left: 0

2024-01-25 21:56 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position: absolute;
принципиально fixed

2024-01-25 21:56 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__wrapper {
.modal__wrapper => .modal__window

2024-01-29 19:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-29 20:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-01-29 20:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-01-30 15:52 UTC, GSemikozov approved these changes

2024-01-30 15:52 UTC, merged