add solution for lection2-sceleton
js-tasks-ru/htmlcss-20231222_svzhloba pull request #6
Opened 2024-01-18 19:23 UTC by Sansamania

2024-01-18 19:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-19 07:33 UTC, GSemikozov requested changes

2024-01-19 07:33 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +  justify-content: space-between;
лишнее

2024-01-19 07:33 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.sceleton__group1 {
такие классы - очень не информативны, надо бы продумать получше) например .sceleton__top, .sceleton__bottom, .sceleton__column

2024-01-19 07:33 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.sceleton__group2, .sceleton__group3 {
если абсолютно одинаковые - то надо ли иметь 2 разных элемента?

2024-01-19 07:33 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.sceleton_item {
.sceleton__item? элемент?

2024-01-19 07:33 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.sceleton__group2 .sceleton_item:first-child {
не нужно привязывать к группам а потом брать первый - сложная выборка, жесткая привязка к другим элементам и порядку в них. Гораздо проще управлять шириной элемента через модификаторы

2024-01-19 17:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-21 17:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-01-25 21:48 UTC, GSemikozov approved these changes

2024-01-25 21:48 UTC, merged